[project]
name = "your-project-name"
version = "0.1.0"
description = "Add a short description"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.136.1",
    "pyjwt>=2.12.1",
    "python-multipart>=0.0.27",
    "pyyaml>=6.0.3",
    "requests>=2.33.1",
    "uvicorn>=0.46.0",
]

[dependency-groups]
dev = [
    "bandit>=1.9.4",
    "pytest>=9.0.3",
    "ruff>=0.15.12",
]
